public abstract class e.f.a.b.a.a {
	 /* .source "SourceFile" */
	 /* # static fields */
	 public static final Integer common_full_open_on_phone;
	 public static final Integer common_google_signin_btn_icon_dark;
	 public static final Integer common_google_signin_btn_icon_dark_focused;
	 public static final Integer common_google_signin_btn_icon_dark_normal;
	 public static final Integer common_google_signin_btn_icon_dark_normal_background;
	 public static final Integer common_google_signin_btn_icon_disabled;
	 public static final Integer common_google_signin_btn_icon_light;
	 public static final Integer common_google_signin_btn_icon_light_focused;
	 public static final Integer common_google_signin_btn_icon_light_normal;
	 public static final Integer common_google_signin_btn_icon_light_normal_background;
	 public static final Integer common_google_signin_btn_text_dark;
	 public static final Integer common_google_signin_btn_text_dark_focused;
	 public static final Integer common_google_signin_btn_text_dark_normal;
	 public static final Integer common_google_signin_btn_text_dark_normal_background;
	 public static final Integer common_google_signin_btn_text_disabled;
	 public static final Integer common_google_signin_btn_text_light;
	 public static final Integer common_google_signin_btn_text_light_focused;
	 public static final Integer common_google_signin_btn_text_light_normal;
	 public static final Integer common_google_signin_btn_text_light_normal_background;
	 public static final Integer googleg_disabled_color_18;
	 public static final Integer googleg_standard_color_18;
