public abstract class c.r.a {
	 /* .source "SourceFile" */
	 /* # static fields */
	 public static final Integer alpha;
	 public static final Integer fastScrollEnabled;
	 public static final Integer fastScrollHorizontalThumbDrawable;
	 public static final Integer fastScrollHorizontalTrackDrawable;
	 public static final Integer fastScrollVerticalThumbDrawable;
	 public static final Integer fastScrollVerticalTrackDrawable;
	 public static final Integer font;
	 public static final Integer fontProviderAuthority;
	 public static final Integer fontProviderCerts;
	 public static final Integer fontProviderFetchStrategy;
	 public static final Integer fontProviderFetchTimeout;
	 public static final Integer fontProviderPackage;
	 public static final Integer fontProviderQuery;
	 public static final Integer fontStyle;
	 public static final Integer fontVariationSettings;
	 public static final Integer fontWeight;
	 public static final Integer layoutManager;
	 public static final Integer recyclerViewStyle;
	 public static final Integer reverseLayout;
	 public static final Integer spanCount;
	 public static final Integer stackFromEnd;
	 public static final Integer ttcIndex;
